# Lab 1 - Python review

## Purpose
The purpose of this class is to strengthen and practice your knowledge of Python, mainly involved in data structures and commands that we will use during the semester.

## Methodology
Review basic operations, data types and programming concepts in Python. Solve programming challenges.

## Results
Fast track to programming in Python.

---

## Setup

### Library import

In [14]:
import numpy as np

---

# Review

1 - Escreva um programa que calcule a soma de todos os números pares de 1 a 100. (Faça duas opções, uma usando o operador `%` e outra não)


In [ ]:
soma = 0
for i in range(2, 101, 2):
    soma += i
print("A soma dos números pares de 1 a 100 é:", soma)

A soma dos números pares de 1 a 100 é: 2550


In [ ]:
soma = 0
for i in range(0, 101):
    if i%2==0:
      soma += i
print("A soma dos números pares de 1 a 100 é:", soma)

A soma dos números pares de 1 a 100 é: 2550


2 - Crie uma função que receba como parâmetro uma lista e retorne o maior elemento.

In [ ]:
def maior_elemento(lista):
    return max(lista)

a = [1,3,0,20,5,8,1,3]

print(maior_elemento(a))

20


3 - Escreva um programa que gere uma lista com os números de 1 a 10 elevados ao quadrado.(use List Comprehension)

In [ ]:
lista_quadrados = [i**2 for i in range(1, 11)]
print(lista_quadrados)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


4 - Implemente uma função que receba duas listas como parâmetros e retorne uma nova lista contendo os elementos comuns entre as duas listas. (utilize a função `set()` e o operador `&`)

In [ ]:
def elementos_comuns(lista1, lista2):
    return list(set(lista1) & set(lista2))

a = [1,3,0,20,5,8,8,3]
b = [3,90,80,5,2]

print(elementos_comuns(a,b))


[3, 5]


5 - Escreva uma função que calcule a média de uma lista de números.

In [ ]:
def media(lista):
    return sum(lista) / len(lista)


print(media(a))

6.166666666666667


6 - Crie uma função que receba um número como parâmetro e retorne `True` se o número for primo e `False` caso contrário.

In [ ]:
def eh_primo(num):
    if num < 2:
      return False

    for i in range(2, int(num**0.5) + 1):
      if num % i == 0:
        return False
    return True


print(eh_primo(5))

True


7 - Implemente uma função que receba uma lista como parâmetro e retorne uma nova lista contendo apenas os elementos únicos.

In [ ]:
def elementos_unicos(lista):
    return list(set(lista))

print(elementos_unicos(a))

[0, 1, 3, 5, 8, 20]


8 - Escreva uma rotina que calcule a soma dos elementos de uma matriz. Faça duas opções, uma com `numpy` e outra sem.

In [ ]:
matriz = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]

soma = 0
for x in matriz:
  soma += sum([y for y in x])

print("A soma dos elementos da matriz é:", soma)

A soma dos elementos da matriz é: 45


In [ ]:
import numpy as np

matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

soma = np.sum(matriz)

print("A soma dos elementos da matriz é:", soma)

A soma dos elementos da matriz é: 45


9 - Crie uma função que receba duas matrizes como parâmetros e retorne a soma das duas matrizes. O que muda se somarmos duas matrizes usando o operador `+` e duas matrizes numpy usando o mesmo operador?

In [ ]:

matriz1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matriz2 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

def soma_matrizes(matriz1, matriz2):
    return matriz1 + matriz2

print(soma_matrizes(matriz1, matriz2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:

matriz1 = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

matriz2 = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

def soma_matrizes(matriz1, matriz2):
    return matriz1 + matriz2

print(soma_matrizes(matriz1, matriz2))

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]


10 - Para que serve o método `numpy.shape()`? É possivel somar duas matrizes com operador `+` com shapes diferentes?

In [ ]:
matriz1 = np.array([[1, 2],
                   [4, 5],
                   [7, 8]])

matriz2 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

def soma_matrizes(matriz1, matriz2):
    return matriz1 + matriz2

print(soma_matrizes(matriz1, matriz2))

ValueError: operands could not be broadcast together with shapes (3,2) (3,3) 

11 - Implemente uma função que receba uma lista como parâmetro e retorne outra lista com os elementos invertidos. Tente fazer em uma linha e usando somente slice.

In [ ]:
matriz = np.array([1, 2, 3])

def elementos_invertidos(lista):
    return lista[::-1]


print(elementos_invertidos(matriz))



[3 2 1]


12 - O que é uma matriz transposta? Escreva um programa que verifique se uma matriz é simétrica.

In [ ]:
def eh_simetrica(matriz):
    return (matriz == matriz.T).all()

matriz = np.array([[1, 2, 3],
                   [2, 5, 6],
                   [3, 6, 9]])

print(eh_simetrica(matriz))

True


13 - Crie uma função que receba uma lista como parâmetro e retorne uma nova lista com os elementos ordenados de forma decrescente.

In [ ]:
def ordena_decrescente(lista):
    return sorted(lista, reverse=True)

a = [3,2,1,50,67,49]

print(ordena_decrescente(a))

[67, 50, 49, 3, 2, 1]


14 - Escreva uma rotina que calcule o produto escalar de dois vetores.

In [ ]:
vetor1 = np.array([1, 2, 3])
vetor2 = np.array([4, 5, 6])

produto_escalar = np.dot(vetor1, vetor2)

print("O produto escalar dos vetores é:", produto_escalar)

O produto escalar dos vetores é: 32


15 - Crie uma função que receba uma lista como parâmetro e retorne `True` se a lista estiver ordenada em ordem crescente, `False` caso contrário.

In [ ]:
def esta_ordenada(lista):
    return all(lista[i] <= lista[i + 1] for i in range(len(lista) - 1))


a = [1,3,2,4]

print(esta_ordenada(a))


False


16 -  Implemente uma função que receba uma matriz como parâmetro e retorne `True` se a matriz for diagonal, `False` caso contrário. Pense em uma soluçao via numpy e via python list.

In [13]:
def eh_diagonal(matriz):
    return (matriz == np.diag(np.diag(matriz))).all()

a = matriz = np.array([[1, 0, 0],
                   [0, 5, 0],
                   [0, 0, 9]])

print(eh_diagonal(a))

NameError: name 'np' is not defined

17 - Crie uma função que receba uma lista como parâmetro e retorne a mediana dos elementos.

In [ ]:
def mediana(lista):
    return np.median(lista)

18 - Crie uma função que receba uma lista como parâmetro e retorne uma nova lista contendo apenas os elementos que são múltiplos de 3.

In [ ]:
def multiplos_de_tres(lista):
    return [x for x in lista if x % 3 == 0]



19 - Escreva um programa que calcule a média móvel de uma lista com uma janela de tamanho `k`.

In [ ]:
def media_movel(lista, k):
    medias = []
    for i in range(len(lista) - k + 1):
        medias.append(sum(lista[i:i+k]) / k)
    return medias


a = [1,2,3,4,5,6]

print(media_movel(a,4))

[2.5, 3.5, 4.5]


20 - Escreva um programa que calcule a soma dos fatoriais de todos os números de 1 a `N`, onde `N` é fornecido pelo usuário.

In [ ]:
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)

def sum_of_factorials(N):
    total_sum = 0
    for i in range(1, N+1):
        total_sum += factorial(i)
    return total_sum

N = int(input("Digite um número inteiro positivo: "))
print("A soma dos fatoriais de 1 a", N, "é:", sum_of_factorials(N))


Digite um número inteiro positivo: 5
A soma dos fatoriais de 1 a 5 é: 153


21 - Usando `while`, escreva um programa que gere um número aleatório entre 1 e 100 e permita que o usuário adivinhe o número. O programa deve fornecer feedback sobre se o palpite do usuário está alto, baixo ou correto. O loop deve continuar até que o usuário adivinhe corretamente. (utilize a biblioteca `random`)

In [ ]:
import random

numero_secreto = random.randint(1, 100)
tentativas = 0

while True:
    palpite = int(input("Adivinhe o número secreto (entre 1 e 100): "))
    tentativas += 1

    if palpite == numero_secreto:
        print("Parabéns! Você acertou o número em", tentativas, "tentativas!")
        break
    elif palpite < numero_secreto:
        print("Tente um número maior.")
    else:
        print("Tente um número menor.")


Adivinhe o número secreto (entre 1 e 100): 4
Tente um número maior.
Adivinhe o número secreto (entre 1 e 100): 40
Tente um número menor.
Adivinhe o número secreto (entre 1 e 100): 20
Tente um número maior.
Adivinhe o número secreto (entre 1 e 100): 30
Tente um número menor.
Adivinhe o número secreto (entre 1 e 100): 33
Tente um número menor.
Adivinhe o número secreto (entre 1 e 100): 32
Tente um número menor.
Adivinhe o número secreto (entre 1 e 100): 31
Tente um número menor.
Adivinhe o número secreto (entre 1 e 100): 25
Tente um número menor.
Adivinhe o número secreto (entre 1 e 100): 24
Tente um número menor.
Adivinhe o número secreto (entre 1 e 100): 23
Tente um número menor.
Adivinhe o número secreto (entre 1 e 100): 22
Parabéns! Você acertou o número em 11 tentativas!


22 - Utilizando apenas list comprehension elaborar uma rotina que filtre números pares em uma lista.

In [ ]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_numbers = [num for num in numbers if num % 2 == 0]
print(even_numbers)

[2, 4, 6, 8, 10]


23 - Utilizando apenas list comprehension, elaborar uma rotina que converta strings para maiúsculas somente se tiverem mais de 5 caracteres. (utilizar `upper()`)

In [ ]:
words = ["apple", "banana", "orange", "kiwi", "strawberry", "peach"]
upper_long_words = [word.upper() if len(word) > 5 else word for word in words]
print(upper_long_words)

['apple', 'BANANA', 'ORANGE', 'kiwi', 'STRAWBERRY', 'peach']


24 - Qual a diferença entre `append` e `+` quando trabalhamos com listas? Explique com código.

Index: 0, Fruit: apple
Index: 1, Fruit: banana
Index: 2, Fruit: orange
Index: 3, Fruit: kiwi
Index: 4, Fruit: strawberry


25 - Utilizando `enumerate()`, crie uma rotina que imprima índices e elementos contidos em uma lista.

In [ ]:
fruits = ["apple", "banana", "orange", "kiwi", "strawberry"]
for index, fruit in enumerate(fruits):
    print(f"Index: {index}, Fruit: {fruit}")

Index: 0, Fruit: apple
Index: 1, Fruit: banana
Index: 2, Fruit: orange
Index: 3, Fruit: kiwi
Index: 4, Fruit: strawberry


26 - Através de um único comprehension, criar uma função que receba uma letra e um string e que conte o número de vezes que a letra aparece no string.

In [ ]:
def cont_letras(sentence,letter_to_count):
  count = sum(1 for _, letter in enumerate(sentence) if letter == letter_to_count)

  return count


print(cont_letras("Hello, how are you?",'o'))


3


27 - Desenvolva um programa que permita ao usuário criar e atualizar uma lista de compras. Ele deve fornecer opções para adicionar novos itens à lista, remover itens existentes e exibir a lista atualizada.

O menu da lista deve ser:

`1. Adicionar Item`

`2. Remover Item`

`3. Exibir Lista de Compras`

`4. Sair`


- Ao selecionar `1` o programa pede ao utilizador o nome do item e quantidade;
- Ao selecionar `2` o programa deve perguntar o nome do item que se quer remover;
- Ao selecionar `3` o programa deve exibir os itens atuais da lista
- Ao selecionar `4` o programa deve sair.
- Ao digitar uma opção não válida o programa deve exibir `Opção inválida. Por favor, escolha novamente.`


In [ ]:
def display_shopping_list(shopping_list):
    print("Lista de Compras:")
    for item, quantity in shopping_list.items():
        print(f"{item}: {quantity}")

def update_shopping_list(shopping_list):
    while True:
        print("\nOpções:")
        print("1. Adicionar Item")
        print("2. Remover Item")
        print("3. Exibir Lista de Compras")
        print("4. Sair")
        choice = input("Escolha uma opção: ")

        if choice == '1':
            item = input("Insira o nome do item: ")
            quantity = input("Insira a quantidade: ")
            shopping_list[item] = quantity
        elif choice == '2':
            item = input("Insira o nome do item que deseja remover: ")
            if item in shopping_list:
                del shopping_list[item]
            else:
                print("Item não encontrado na lista.")
        elif choice == '3':
            display_shopping_list(shopping_list)
        elif choice == '4':
            break
        else:
            print("Opção inválida. Por favor, escolha novamente.")

shopping_list = {}
update_shopping_list(shopping_list)



Opções:
1. Adicionar Item
2. Remover Item
3. Exibir Lista de Compras
4. Sair
Escolha uma opção: 7
Opção inválida. Por favor, escolha novamente.

Opções:
1. Adicionar Item
2. Remover Item
3. Exibir Lista de Compras
4. Sair
Escolha uma opção: 4
