# Lab 1 - Python review

## Purpose
The purpose of this class is to strengthen and practice your knowledge of Python, mainly involved in data structures and commands that we will use during the semester.

## Methodology
Review basic operations, data types and programming concepts in Python. Solve programming challenges.

## Results
Fast track to programming in Python.

---

## Setup

### Library import

In [2]:
import numpy as np
import operator as op

---

# Review

1 - Escreva um programa que calcule a soma de todos os números pares de 1 a 100. (Faça duas opções, uma usando o operador `%` e outra não)


In [3]:
soma = 0

for x in range(1,101):
    if (x % 2 == 0):
        soma += x

print(soma)

2550


In [4]:
# uma comprehension pode ter como resultado uma lista ou um dicionario

print(sum([x for x in range(1,101) if (x % 2 == 0)]))

2550


In [5]:
soma = 0

for x in range(0,101,2):
    soma += x

print(soma)

2550


2 - Crie uma função que receba como parâmetro uma lista e retorne o maior elemento.

In [6]:
a = [1,3,0,20,5,8,1,3]

def maiorLista(a):
    maiorTemp = -1

    for x in a:
        if (x > maiorTemp):
            maiorTemp = x

    return maiorTemp

print(maiorLista(a))

20


3 - Escreva um programa que gere uma lista com os números de 1 a 10 elevados ao quadrado.(use List Comprehension)

In [7]:
[x**2 for x in range(1,11)]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

4 - Implemente uma função que receba duas listas como parâmetros e retorne uma nova lista contendo os elementos comuns entre as duas listas. (utilize a função `set()` e o operador `&`)

In [8]:
a = [1,3,0,20,5,2,8,3]
b = [3,90,80,5,2]

def elementosComunsListas(a,b):
    novaLista = []

    a = set(a)
    b = set(b)
    
    for x in a:
        if (x in b):
            novaLista.append(x)

    return novaLista

print(elementosComunsListas(a,b))

[2, 3, 5]


In [9]:
a = [1,3,0,20,5,2,8,3]
b = [3,90,80,5,2]

def elementosComunsListas(a,b):
    return list(set(a) & set(b))

print(elementosComunsListas(a,b))

[2, 3, 5]


5 - Escreva uma função que calcule a média de uma lista de números.

In [10]:
a = [1,3,0,20,5,2,8,3]

def media(a):
    return sum(a)/len(a)

print(media(a))

5.25


6 - Crie uma função que receba um número como parâmetro e retorne `True` se o número for primo e `False` caso contrário.

In [11]:
def primo(num):
    if num > 1:
        for i in range(2, num):   
            if (num % i) == 0:
                return False
                break
        else:
            return True
    else:
        return False
    
print(primo(9))
print(primo(11))

False
True


7 - Implemente uma função que receba uma lista como parâmetro e retorne uma nova lista contendo apenas os elementos únicos.

In [12]:
a = [1,3,0,20,5,8,8,3]

def elementosUnicosLista(a):
    novaLista = []

    for x in a:
        if (op.countOf(a, x) < 2):
             novaLista.append(x)

    return novaLista

print(elementosUnicosLista(a))

[1, 0, 20, 5]


8 - Escreva uma rotina que calcule a soma dos elementos de uma matriz. Faça duas opções, uma com `numpy` e outra sem.

In [13]:
a = np.matrix([[1,2],[3,4]])

soma = np.sum(a)

print(soma)

10


In [14]:
a = [[1,2],[3,4]]

soma = sum([sum(x) for x in a])

print(soma)

10


9 - Crie uma função que receba duas matrizes como parâmetros e retorne a soma das duas matrizes. O que muda se somarmos duas matrizes usando o operador `+` e duas matrizes numpy usando o mesmo operador?

In [15]:
a = [[1,2],[3,4]]
b = [[2,1],[4,3]]

def somaMatrix(a,b):
    return a+b

print(somaMatrix(a,b))

[[1, 2], [3, 4], [2, 1], [4, 3]]


In [16]:
a = np.matrix([[1,2],[3,4]])
b = np.matrix([[2,1],[4,3]])

def somaMatrix(a,b):
    return a+b

print(somaMatrix(a,b))

[[3 3]
 [7 7]]


10 - Para que serve o método `numpy.shape()`? É possivel somar duas matrizes com operador `+` com shapes diferentes?

In [19]:
#numpy.shape() retorna um tuplo com a quantidade de linhas e colunas
a = np.matrix([[1,2],[3,4]])
print(np.shape(a))

#a1 = np.matrix([[1,2,2],[3,4]])
#b1 = np.matrix([[2,1],[4,3]])
#soma1 = b + c não é possivel somar duas matrizes do numpy com shapes diferentes
#print(soma1)

a2 = [[1,2,2],[3,4]]
b2 = [[2,1],[4,3]]
soma2 = a2 + b2 #é possivel somar duas matrizes "normais" com shapes diferentes
print(soma2)

(2, 2)
[[1, 2, 2], [3, 4], [2, 1], [4, 3]]


11 - Implemente uma função que receba uma lista como parâmetro e retorne outra lista com os elementos invertidos. Tente fazer em uma linha e usando somente slice.

In [ ]:
a = [1,3,0,2,5,3]

def inverterLista(a):
    return a[::-1]

print(inverterLista(a))

[3, 5, 2, 0, 3, 1]


12 - O que é uma matriz transposta? Escreva um programa que verifique se uma matriz é simétrica.

In [ ]:
a = np.matrix([[1,2,3],[2,3,4]])

print(a)

b = np.transpose(a)

print(b)

[[1 2 3]
 [2 3 4]]
[[1 2]
 [2 3]
 [3 4]]


In [44]:
a = np.matrix([[1,2,3],[2,3,4]])
b = np.matrix([[1,0,0],[0,1,0],[0,0,1]])

def matrixSimetrica(x):
    xTrans = np.array(x).transpose()
    if np.array_equal(x, xTrans):
        return True
    return False

print(matrixSimetrica(a))
print(matrixSimetrica(b))

False
True


13 - Crie uma função que receba uma lista como parâmetro e retorne uma nova lista com os elementos ordenados de forma decrescente.

In [55]:
a = [1,3,0,2,5]

def ordenarDecrescente(a):    
    a.sort(reverse=True)
    return a

print(ordenarDecrescente(a))

[5, 3, 2, 1, 0]


14 - Escreva uma rotina que calcule o produto escalar de dois vetores.

In [56]:
vetor1 = [1, 2, 3]
vetor2 = [1, 2, 3]

def produtoEscalar(vetor1, vetor2):
    produto = 0

    for i in range(len(vetor1)):
        produto += vetor1[i] * vetor2[i]

    return produto

print(produtoEscalar(vetor1, vetor2))

14


15 - Crie uma função que receba uma lista como parâmetro e retorne `True` se a lista estiver ordenada em ordem crescente, `False` caso contrário.

In [62]:
a = [1,3,0,2,5]
b = [1,3,5,6,9]

def estaOrdenadaCrescente(lista):
    lista2 = lista.copy()
    lista.sort()

    if lista2 == lista:
        return True
    return False

print(estaOrdenadaCrescente(a))
print(estaOrdenadaCrescente(b))

False
True


16 -  Implemente uma função que receba uma matriz como parâmetro e retorne `True` se a matriz for diagonal, `False` caso contrário. Pense em uma soluçao via numpy e via python list.

In [63]:
matriz1 = np.array([[1, 0, 0],[0, 2, 0],[0, 0, 3]])
matriz2 = np.array([[1, 0, 0],[0, 2, 1],[0, 0, 3]])

def matrizDiagonalNumpy(matriz):
    if matriz.shape[0] != matriz.shape[1]:
        return False
    return np.all(matriz - np.diag(np.diag(matriz)) == 0)

print(matrizDiagonalNumpy(matriz1))
print(matrizDiagonalNumpy(matriz2))

True
False


In [64]:
matriz1 = np.array([[1, 0, 0],[0, 2, 0],[0, 0, 3]])
matriz2 = np.array([[1, 0, 0],[0, 2, 1],[0, 0, 3]])

def matrizDiagonalPython(matriz):
    if len(matriz) != len(matriz[0]):
        return False
    
    for i in range(len(matriz)):
        for j in range(len(matriz[0])):
            if i != j and matriz[i][j] != 0:
                return False
    return True

print(matrizDiagonalPython(matriz1))
print(matrizDiagonalPython(matriz2))

True
False


17 - Crie uma função que receba uma lista como parâmetro e retorne a mediana dos elementos.

In [65]:
lista = [1,2,3,4,5,6,7]
lista2 = [1,2,5,6,7,8,8,10]

def mediana(lista):
    lista_ordenada = sorted(lista)

    if len(lista_ordenada) % 2 != 0:
        return lista_ordenada[len(lista_ordenada) // 2]
    else:
        meio_inferior = lista_ordenada[len(lista_ordenada) // 2 - 1]
        meio_superior = lista_ordenada[len(lista_ordenada) // 2]
        return (meio_inferior + meio_superior) / 2

print(mediana(lista))
print(mediana(lista2))

4
6.5


18 - Crie uma função que receba uma lista como parâmetro e retorne uma nova lista contendo apenas os elementos que são múltiplos de 3.

In [67]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12]

def listaMult3(lista):
    mult3 = []
    
    for x in lista:
        if x % 3 == 0:
            mult3.append(x)
    return mult3

print(listaMult3(lista))

[3, 6, 9, 12]


19 - Escreva um programa que calcule a média móvel de uma lista com uma janela de tamanho `k`.

In [68]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

def mediaMovel(lista, k):
    medias = []

    for i in range(len(lista) - k + 1):
        janela = lista[i:i+k]
        media = sum(janela) / k
        medias.append(media)

    return medias

print(mediaMovel(lista,3))

[2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]


20 - Escreva um programa que calcule a soma dos fatoriais de todos os números de 1 a `N`, onde `N` é fornecido pelo usuário.

In [72]:
def fatorial(n):
    if n == 0:
        return 1
    else:
        return n * fatorial(n - 1)

def soma_fatoriais(N):
    soma = 0
    for i in range(1, N + 1):
        soma += fatorial(i)
    return soma

print(soma_fatoriais(3))

9


21 - Usando `while`, escreva um programa que gere um número aleatório entre 1 e 100 e permita que o usuário adivinhe o número. O programa deve fornecer feedback sobre se o palpite do usuário está alto, baixo ou correto. O loop deve continuar até que o usuário adivinhe corretamente. (utilize a biblioteca `random`)

In [73]:
import random

numero_secreto = random.randint(1, 100)
palpite = None

while palpite != numero_secreto:
    palpite = int(input("Tente adivinhar o número (entre 1 e 100): "))

    if palpite < numero_secreto:
        print("Palpite baixo")
    elif palpite > numero_secreto:
        print("Palpite alto")
    else:
        print("Palpite correto")


Palpite baixo
Palpite baixo
Palpite alto
Palpite alto
Palpite baixo
Palpite baixo
Palpite baixo
Palpite alto
Palpite correto


22 - Utilizando apenas list comprehension elaborar uma rotina que filtre números pares em uma lista.

In [75]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

numeros_pares = [x for x in numbers if x % 2 == 0]

print(numeros_pares)

[2, 4, 6, 8, 10]


23 - Utilizando apenas list comprehension, elaborar uma rotina que converta strings para maiúsculas somente se tiverem mais de 5 caracteres. (utilizar `upper()`)

In [76]:
words = ["apple", "banana", "orange", "kiwi", "strawberry", "peach"]

wordsUpper = [s.upper() if len(s) > 5 else s for s in words]

print(wordsUpper)

['apple', 'BANANA', 'ORANGE', 'kiwi', 'STRAWBERRY', 'peach']


24 - Qual a diferença entre `append` e `+` quando trabalhamos com listas? Explique com código.

In [78]:
# append
listaAppend = [1, 2, 3]
listaAppend.append(4)
print(listaAppend)

# +
listaSoma = [1, 2, 3]
listaSomaNova = listaSoma + [4] # só se pode somar lista com lista
print(listaSomaNova)

[1, 2, 3, 4]
[1, 2, 3, 4]


25 - Utilizando `enumerate()`, crie uma rotina que imprima índices e elementos contidos em uma lista.

In [80]:
fruits = ["apple", "banana", "orange", "kiwi", "strawberry"]

for idx, x in enumerate(fruits):
    print("[", idx, "]", x)

[ 0 ] apple
[ 1 ] banana
[ 2 ] orange
[ 3 ] kiwi
[ 4 ] strawberry


26 - Através de um único comprehension, criar uma função que receba uma letra e um string e que conte o número de vezes que a letra aparece no string.

In [82]:
def contarLetra(string,letra):
    numLetras = [1 for caractere in string if caractere == letra]
    return sum(numLetras)

print(contarLetra("carolina","a"))

2


27 - Desenvolva um programa que permita ao usuário criar e atualizar uma lista de compras. Ele deve fornecer opções para adicionar novos itens à lista, remover itens existentes e exibir a lista atualizada.

O menu da lista deve ser:

`1. Adicionar Item`

`2. Remover Item`

`3. Exibir Lista de Compras`

`4. Sair`


- Ao selecionar `1` o programa pede ao utilizador o nome do item e quantidade;
- Ao selecionar `2` o programa deve perguntar o nome do item que se quer remover;
- Ao selecionar `3` o programa deve exibir os itens atuais da lista
- Ao selecionar `4` o programa deve sair.
- Ao digitar uma opção não válida o programa deve exibir `Opção inválida. Por favor, escolha novamente.`


In [83]:
def adicionarItem(listaCompras):

    item = input("Digite o nome do item: ")
    quantidade = int(input("Digite a quantidade: "))

    listaCompras[item] = quantidade
    print(f"{quantidade} {item}(s) adicionado(s) à lista de compras.")

def removerItem(listaCompras):

    item = input("Digite o nome do item que deseja remover: ")
    
    if item in listaCompras:
        del listaCompras[item]
        print(f"{item} removido da lista de compras.")
    else:
        print(f"{item} não está na lista de compras.")

def exibirLista(listaCompras):

    print("Lista de Compras:")
    for item, quantidade in listaCompras.items():
        print(f"{quantidade} {item}")
    if not listaCompras:
        print("Lista de compras vazia.")

def main():
    lista_compras = {}
    
    while True:
        print("\nMenu da Lista de Compras:")
        print("1. Adicionar Item")
        print("2. Remover Item")
        print("3. Exibir Lista de Compras")
        print("4. Sair")
        opcao = input("Escolha uma opção: ")

        if opcao == "1":
            adicionarItem(lista_compras)
        elif opcao == "2":
            removerItem(lista_compras)
        elif opcao == "3":
            exibirLista(lista_compras)
        elif opcao == "4":
            break
        else:
            print("Opção inválida. Por favor, escolha novamente.")

if __name__ == "__main__":
    main()



Menu da Lista de Compras:
1. Adicionar Item
2. Remover Item
3. Exibir Lista de Compras
4. Sair
5 pao(s) adicionado(s) à lista de compras.

Menu da Lista de Compras:
1. Adicionar Item
2. Remover Item
3. Exibir Lista de Compras
4. Sair
Lista de Compras:
5 pao

Menu da Lista de Compras:
1. Adicionar Item
2. Remover Item
3. Exibir Lista de Compras
4. Sair
pao removido da lista de compras.

Menu da Lista de Compras:
1. Adicionar Item
2. Remover Item
3. Exibir Lista de Compras
4. Sair
Lista de Compras:
Lista de compras vazia.

Menu da Lista de Compras:
1. Adicionar Item
2. Remover Item
3. Exibir Lista de Compras
4. Sair
